apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: tech
  labels:
    app: wp-mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
  - targetPort: 3306
    port: 3306


   
