apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  namespace: tech
  labels:
    app: wp
    tier: frontend
spec:
  selector:
    app: wp
  type: NodePort
  ports:
  - targetPort: 80
    port: 80



   
